### PR TITLE
moved to base

### PR DESCRIPTION
**Pull request by siddhartha-gadgil**
I have moved the original files to base as that is more convenient and the gh-pages view is more natural (my copy is at https://siddhartha-gadgil.github.io/QED/QED.html). I have also corrected a typo in `gui.js` which caused the app to not run, and added bootstrap styling.

### CODE REVIEW

**Comment by cjerdonek** [comment]
I would encourage you to use the "docs" directory format for GitHub pages (by moving the html and js pages to a `docs` directory). It will be a bit simpler since it doesn't involve syncing to a separate branch. Also, it's better practice IMO to put source files in a subdirectory rather than at the top level of a repo. That way you can put other files in the repo without also adding them to the site's files.

**Comment by siddhartha-gadgil** [comment]
I agree. Will make the change

**Comment by siddhartha-gadgil** [comment]
done

**Comment by cjerdonek** [comment]
And update the README's text describing the file layout.

**Comment by siddhartha-gadgil** [comment]
Done.

**Comment by teorth** [comment]
OK, it looks like it works, though the layout of the HTML elements is different from the version I have on my own web site, I guess github adds some additional CSS styling or something?

**Comment by cjerdonek** [comment]
I think GitHub just publishes it as is. I'm guessing the difference you're seeing is due to this change by @siddhartha-gadgil in the PR you accepted: https://github.com/teorth/QED/pull/1/commits/7722db92d0a3124a6cb8c5d08bd480ef5fe7c20d
(It's better if PR's are restricted to one thing at a time rather than changing multiple things at once so it's easier to see what is changing.)

**Comment by teorth** [comment]
Ah, yes that's what happened, thanks for clearing it up.

**Pull request merged**
